### ISSUE TITLE
problem with Nuxtjs

### ISSUE THREAD

**Issue by tsimenis** [AlexandreBonaventure/vue-scrollmonitor#1]
Hey there, 

I've installed this as a plugin in Nuxtjs and although it seems to work in the browser I get this error in the server:

<img width="1078" alt="vuescrollmonitor" src="https://user-images.githubusercontent.com/5978397/32700028-3bcf49cc-c7bf-11e7-9b74-773d19a4c3e6.png">

Any idea how to solve this?

Thanks in advance

**Comment by AlexandreBonaventure** [comment]
Thanks for using this.
Yes it was not design for taking SSR into account but I'll check this to see if can drop a release to support this.

**Comment by tsimenis** [comment]
That would be great, I would really like to use it on a current project but I don't know how I would fix the server error. 

If you have any update please let me know

thanks

**Comment by tsimenis** [comment]
Hey @AlexandreBonaventure do you maybe have an update on this?

**Comment by AlexandreBonaventure** [comment]
Yes i'm testing the lib with nuxt right now, I'll give feedback asap

**Comment by AlexandreBonaventure** [comment]
Ouf, that one was very tough to debug !
Seems like there is a regression in vue@2.4.x. Since nuxt is tied with some specific version of vue it's difficult.
BUT, you should try new release I've tested it with nuxt@1.0.rc-11 + vue@2.5.9
And it's working :)

**Comment by AlexandreBonaventure** [comment]
![screenshot](https://preview.ibb.co/f6gzSw/Capture_d_e_cran_2017_12_06_a_16_45_59.png)
